### ISSUE TITLE
Add and changes

### ISSUE THREAD

**Issue by cesarpe** [m-thalmann/windowjs#1]
454/5000
Hello
What a good program you have done. I congratulate you.
I would like to ask you if you can expand some features.
as they are:
- Make the focus activate when there are more forms.
- Make a list of forms
- Have access to controls from events
- show the minimized forms on the screen as does the windows.
With my little knowledge of JS I have done some of these things but I would like them to be part of the code.
Thank you.
Cesar

**Comment by m-thalmann** [comment]
Hey @cesarpe, sorry for my very late response. This library is intended to provide the basics for displaying simple windows in the browser. Everything more specific (like your requests) is up to its user. Therefore I won't integrate those changes into the repo.
