### ISSUE TITLE
Bringing windows to top

### ISSUE THREAD

**Issue by abulka** [m-thalmann/windowjs#2]
Great component, thanks.

When I have multiple windows/dialogs I'd like the one I click on to become 'selected' and come to the front with 'always_on_top', so I developed this

```javascript
function gotop(win) {
    console.log('gotop', win)
    // Logic for switching window and bringing the clicked on window to the front
    // loop through all wins and set false, except for this one
    wins.forEach(function (w) {
        if (w == win) {
            win.changeOption('always_on_top', true);
            win.changeOption('selected', true);
        }
        else {
            w.changeOption('always_on_top', false);
            w.changeOption('selected', false);
        }
    })

}

```
 
I keep the windows in an array `wins`.
```javascript
let wins = []
const win = new Window("Untitled", { ...
wins.push(win)
```

Whilst the `gotop` function works in bringing the clicked on window to the front, the ordering of the remaining windows is not always intuitive. Other background windows may randomly switch z-order position, leading to slight user confusion.

Any thoughts on how I can bring the clicked on window to the front and keep the remaining other windows in their current z-order?

**Comment by m-thalmann** [comment]
Hi @abulka, I see. I will look into this.

**Comment by abulka** [comment]
Thanks. I also noticed that setting `w.changeOption('always_on_top', false);` sets the z-order too far back?, so my inactive windows disappears behind other html elements. Demo video:

https://user-images.githubusercontent.com/11467530/109231373-93dab980-781a-11eb-9682-49356b821428.mp4

**Comment by m-thalmann** [comment]
Hey @abulka. I've added a `isSelected` function. You can now simply do the following, after all windows have been initialized and shown:
```js
var windows = ...; // array of windows

windows.forEach(function(window){
  window.getContainer().onmousedown = function() {
    if(window.isSelected()){
      return;
    }

    window.changeOption("selected", true);

    windows.forEach(function(win){
      if(window !== win){
        win.changeOption("selected", false);
      }
    });
  };
});
```
This will select the focused window and deselect all others.

Since this does not involve the always_on_top option, this works correctly.

**Comment by nedrylandProject** [comment]
It works, Thanks guys, great job there Matthias.
