### ISSUE TITLE
Crash when not enough room to render a window

### ISSUE THREAD

**Issue by abulka** [m-thalmann/windowjs#3]
I get a crash at ` options.position.y = 0;` when there is not enough room to render a window e.g. when I have the Chrome debugging console visible, taking up screen space.

```
window.js:696 Uncaught TypeError: Cannot set property 'y' of undefined
    at updateSize (window.js:696)
    at Window.reload (window.js:238)
    at new Window (window.js:1045)
    ...
```

Interestingly this is the same error you get if you forget to set the CSS with
```css
html, 
body {
    height: 100%;
}
```

I'm reporting this just in case others run into this - I spent hours trying to figure out what was going on using the Chrome developer tools when in fact the developer tools themselves were causing the problem!  Perhaps a more helpful message could be emitted to the console, like 'Not enough space to draw window'?

**Comment by m-thalmann** [comment]
There was a problem with the options object
