### ISSUE TITLE
Resize cursor appears outside of bounds of window

### ISSUE THREAD

**Issue by abulka** [m-thalmann/windowjs#4]
Sorry to raise another issue... 

The resize cursor appears outside of the bounds of window e.g.

<img width="274" alt="Screen Shot 2021-02-26 at 10 53 35 am" src="https://user-images.githubusercontent.com/11467530/109235191-4b72ca00-7821-11eb-9e30-4539aaa0a594.png">

This is non standard UI design and confuses users who are trying to resize windowjs windows. 

More seriously it can cause the mousemove and other events to be sent to html elements outside the window. This sometimes causes weird unwanted interactions. For example the resizing of a window sometimes breaks where the window is stuck in resize mode even though the cursor is free of the window edge area and interacting with other components. Very hard to get out of this situation.

**Comment by m-thalmann** [comment]
This is due to the resize-handle elements. I shrinked them to 3px. This can later also be edited in the css file.
