### ISSUE TITLE
Setting initial window position no longer works

### ISSUE THREAD

**Issue by abulka** [m-thalmann/windowjs#5]
A couple of bugs re window positioning seem to have been introduced recently.

## Centering a window by omitting position option no longer works

Setting the window position to be the center of the screen, by omitting the `position` option no longer works after 19b62de3c50b47b8e99c3b11faf47048651b8b55 

```javascript
if(typeof options.position !== "object"){
  options.position = {
    x: 0,
    y: 0
  };
}
```

The above code breaks the initial nice, centering of a window, when you don't specify an initial position.  All such windows end up at 0,0 rather than in the center of the screen. The useful windowjs code
```javascript
options.position = { x: (parent.offsetWidth / 2 - container.offsetWidth / 2), y: (parent.offsetHeight / 2 - container.offsetHeight / 2) };
```
is thus wasted.

## Setting the initial window position is broken

Setting the initial window position e.g.

```javascript
new Window("Title", {
    state: WindowState.NORMAL,
    size: {
        width: 500,
        height: 250
    },
    position : {x: 20, y: 20},
   ...
})
```

is broken after f417b38bec7cf67f1836a44ff83cabbfe29ed78c and no longer works - every window appears at 0,0 due to the introduction of this code:

```javascript
if(typeof options.position.x !== "object"){
  options.position.x = 0;
}
if(typeof options.position.y !== "object"){
  options.position.y = 0;
}
```

The above code expects `position` to be an object (fair enough) and also wants the `x` and `y` values to be objects too? - which isn't right. `x` and `y` are actually numbers e.g. `position : {x: 20, y: 20}`. Perhaps the code should be checking for type `"number"`, though if the user hasn't specified position as an option this code will break, so the two matters raised in this GitHub issue are related.

The windowjs library seems to work better without these two changes!

**Comment by m-thalmann** [comment]
You are absolutely right. I will fix this asap.
